language: python
os:
  - linux
  - osx
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
matrix:
  exclude:
  - os: osx
    python: "3.3"
  - os: osx
    python: "3.4"
  - os: osx
    python: "3.5"
  - os: osx
    python: "3.6"
  - os: osx
    python: "3.7"
before_install:
  - pip install mypy flake8
  - make
  - ./static_tests.py
install: exit 0
script: exit 0
